---
- name: Hello World Playbook
  hosts: localhost
  connection: local
  gather_facts: no

 
  tasks:
    - name: Print hello world
      debug:
        msg: "hello world from Ansible"

    - name: Create a file with hello world message
      copy:
        content: "hello world from ansible"
        dest: "/tmp/hello_world.txt"

    - name: read the content of the file
      command: cat /tmp/hello_world.txt
      register: file_content

    - name: Display file content
      debug:
        var: file_content.stdout_lines