---
- name: Provision AWS Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/main.yml

  roles:
    - vpc
    - ec2

- name: Configure Web Server
  hosts: webserver
  become: yes
  remote_user: ec2-user
  vars_files:
    - vars/main.yml

  roles:
    - webserver