---
- name: Create an S3 Bucket
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    bucket_name: my-ansible-created-bucket-{{ 999 | random }}
    region: eu-west-2  # Replace with your preferred AWS region

  tasks:
    - name: Create S3 bucket
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        region: "{{ region }}"
        versioning: true
        tags:
          Environment: Test
          CreatedBy: Ansible
      register: s3_result

    - name: Display S3 bucket info
      debug:
        var: s3_result