version: '3'

services:
  app1:
    image: my-demo-server
    ports:
      - "8081:8081"  # Two spaces for indentation
  app2:
    image: my-demo-server2
    ports:
      - "8082:8081"  # Two spaces for indentation
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  my-network:
    external: true
