---
- name: Create S3 Bucket
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - amazon.aws

  vars:
    bucket_name: "my-unique-bucket-name-{{ 999 | random }}"
    region: "eu-west-1"  # Change this to your preferred region

  tasks:
    - name: Create S3 bucket
      amazon.aws.s3_bucket:
        name: "{{ bucket_name }}"
        region: "{{ region }}"
        versioning: true
      register: s3_result

    - name: Display S3 bucket creation result
      debug:
        var: s3_result

    - name: List S3 buckets
      command: aws s3 ls
      register: s3_list
      changed_when: false

    - name: Display S3 bucket list
      debug:
        var: s3_list.stdout_lines