---
- name: List S3 buckets and create IAM user
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - amazon.aws
  tasks:
    - name: Create IAM user
      amazon.aws.iam_user:
        name: "tonytime"
      register: iam_user_result