---
- name: Create IAM User and Group
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    user_name: "test-user-{{ 999 | random }}"
    group_name: "test-group-{{ 999 | random }}"
  tasks:
    - name: Create IAM group
      community.aws.iam_group:
        name: "{{ group_name }}"
        state: present

    - name: Create IAM user
      community.aws.iam_user:
        name: "{{ user_name }}"
        state: present
      register: new_user

    - name: Add user to group
      community.aws.iam_group:
        name: "{{ group_name }}"
        users:
          - "{{ user_name }}"
        state: present

    - name: Create access key for user
      community.aws.iam_access_key:
        user_name: "{{ user_name }}"
        state: present
      register: user_access_key

    - name: Display new user info
      ansible.builtin.debug:
        var: new_user

    - name: Display access key info (DO NOT SHARE IN PRODUCTION)
      ansible.builtin.debug:
        msg: "Access Key: {{ user_access_key.access_key }} / Secret: {{ user_access_key.secret_key }}"