---
- name: Create IAM User and Group
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    user_name: "test-user-{{ 999 | random }}"
    group_name: "test-group-{{ 999 | random }}"
  tasks:
    - name: Create IAM group
      amazon.aws.iam_group:
        name: "{{ group_name }}"
        state: present
      register: group_creation

    - name: Display group creation result
      ansible.builtin.debug:
        var: group_creation

    - name: Create IAM user
      amazon.aws.iam_user:
        name: "{{ user_name }}"
        state: present
      register: user_creation

    - name: Display user creation result
      ansible.builtin.debug:
        var: user_creation

    - name: Create access key for user
      amazon.aws.iam_access_key:
        user_name: "{{ user_name }}"
        state: present
      register: user_access_key

    - name: Display access key info (DO NOT SHARE IN PRODUCTION)
      ansible.builtin.debug:
        msg: "Access Key: {{ user_access_key.access_key }} / Secret: {{ user_access_key.secret_key }}"